variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  DOCKER_HUB_TAG: jpflouret/update-route53:$CI_COMMIT_SHORT_SHA
  DOCKER_HUB_LATEST: jpflouret/update-route53:latest

stages:
  - build
  - hub_push_ref
  - hub_push_latest

build:
  stage: build
  image: docker:latest
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build --pull -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

push_ref:
  stage: hub_push_ref
  image: docker:latest
  only:
    - main
  except:
    - schedules
  before_script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_API_KEY
  script:
    - docker tag $IMAGE_TAG $DOCKER_HUB_TAG
    - docker push $DOCKER_HUB_TAG

push_latest:
  stage: hub_push_latest
  image: docker:latest
  when: manual
  only:
    - main
  except:
    - schedules
  before_script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_API_KEY
  script:
    - docker tag $IMAGE_TAG $DOCKER_HUB_LATEST
    - docker push $DOCKER_HUB_LATEST
