variables:
  DOCKER_HUB_REPO: jpflouret/update-route53

stages:
  - build
  - push

before_script:
  - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

build:
  stage: build
  image: docker:latest
  script:
    - >
      docker build
      --pull
      --cache-from $CI_REGISTRY_IMAGE:latest
      --label "org.opencontainers.image.title=$CI_PROJECT_TITLE"
      --label "org.opencontainers.image.created=$CI_JOB_STARTED_AT"
      --label "org.opencontainers.image.revision=$CI_COMMIT_SHA"
      --label "org.opencontainers.image.version=$CI_COMMIT_REF_NAME"
      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

push_latest:
  variables:
    GIT_STRATEGY: none
  stage: push
  image: docker:latest
  only:
    - main
  except:
    - schedules
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest

hub_push_latest:
  variables:
    GIT_STRATEGY: none
  stage: push
  image: docker:latest
  only:
    - main
  except:
    - schedules
  before_script:
    - echo -n $DOCKER_HUB_API_KEY | docker login -u $DOCKER_HUB_USER --password-stdin
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $DOCKER_HUB_REPO:latest
    - docker push $DOCKER_HUB_REPO:latest

push_tag:
  variables:
    GIT_STRATEGY: none
  stage: push
  only:
    - tags
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME

hub_push_tag:
  variables:
    GIT_STRATEGY: none
  stage: push
  only:
    - tags
  before_script:
    - echo -n $DOCKER_HUB_API_KEY | docker login -u $DOCKER_HUB_USER --password-stdin
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $DOCKER_HUB_REPO:$CI_COMMIT_REF_NAME
    - docker push $DOCKER_HUB_REPO:$CI_COMMIT_REF_NAME
