variables:
  DOCKER_HUB_REPO: jpflouret/update-route53
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

stages:
  - build
  - push

before_script:
  - sleep 5
  - docker info
  - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  - echo -n $DOCKER_HUB_API_KEY | docker login -u $DOCKER_HUB_USER --password-stdin

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script: |
    if [ "$CI_PIPELINE_SOURCE" != "schedule" ]; then
      if [ "$CI_COMMIT_TAG" != "" ]; then
        GIT_PUSH_TAGS="$GIT_PUSH_TAGS --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
        HUB_PUSH_TAGS="$HUB_PUSH_TAGS --tag $DOCKER_HUB_REPO:$CI_COMMIT_TAG"
      elif [ "$CI_COMMIT_REF_NAME" != "" ]; then
        GIT_PUSH_TAGS="$GIT_PUSH_TAGS --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
        HUB_PUSH_TAGS="$HUB_PUSH_TAGS --tag $DOCKER_HUB_REPO:$CI_COMMIT_REF_NAME"
      fi
      if [ "$CI_COMMIT_BRANCH" = "main" ]; then
        GIT_PUSH_TAGS="$GIT_PUSH_TAGS --tag $CI_REGISTRY_IMAGE:latest"
        HUB_PUSH_TAGS="$HUB_PUSH_TAGS --tag $DOCKER_HUB_REPO:latest"
        PUSH_TAGS="$GIT_PUSH_TAGS $HUB_PUSH_TAGS"
      else
        PUSH_TAGS="$GIT_PUSH_TAGS"
      fi
    fi
    if [ "$PUSH_TAGS" != "" ]; then
      PUSH_TAGS="--push $PUSH_TAGS"
    fi
    docker context create build-context
    docker buildx create --name buildx-instance --driver docker-container --use build-context
    docker buildx build \
      --pull \
      --platform linux/arm64/v8,linux/amd64 \
      --label "org.opencontainers.image.title=$CI_PROJECT_TITLE" \
      --label "org.opencontainers.image.created=$CI_JOB_STARTED_AT" \
      --label "org.opencontainers.image.revision=$CI_COMMIT_SHA" \
      --label "org.opencontainers.image.version=$CI_COMMIT_REF_NAME" \
      $PUSH_TAGS \
      .
