apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "update-route53.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "update-route53.name" . }}
    helm.sh/chart: {{ include "update-route53.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  DNS_NAME: {{ .Values.dnsName | quote }}
  DNS_TTL: {{ .Values.dnsTTL | quote }}
  HOSTED_ZONE_ID: {{ .Values.hostedZoneId | quote }}
{{- if .Values.chechIPURL }}
  CHECK_IP: {{ .Values.chechIPURL | quote }}
{{- end }}
{{- if .Values.sleepPeriod }}
  SLEEP_PERIOD: {{ .Values.sleepPeriod | quote }}
{{- end }}
