{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "update-route53.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "update-route53.name" . }}
    helm.sh/chart: {{ include "update-route53.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
{{- if .Values.secret.accessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.secret.accessKeyId | b64enc | quote }}
{{- end }}
{{- if .Values.secret.secretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secret.secretAccessKey | b64enc | quote }}
{{- end }}
{{- if .Values.secret.awsRegion }}
  AWS_DEFAULT_REGION: {{ .Values.secret.awsRegion | b64enc | quote }}
{{- end }}
{{- end -}}
